# Docker Compose for Test Environment
# Isolated test databases and services

version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: thai-energy-test-postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 
      - postgres
      - -c
      - max_connections=100
      - -c
      - shared_buffers=128MB
      - -c
      - log_statement=all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: thai-energy-test-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Test database for isolation testing
  postgres-isolation:
    image: postgres:15-alpine
    container_name: thai-energy-isolation-postgres
    environment:
      POSTGRES_DB: isolation_test_db
      POSTGRES_USER: isolation_user
      POSTGRES_PASSWORD: isolation_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_isolation_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isolation_user -d isolation_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Performance test database (optimized for load testing)
  postgres-performance:
    image: postgres:15-alpine
    container_name: thai-energy-performance-postgres
    environment:
      POSTGRES_DB: perf_test_db
      POSTGRES_USER: perf_user
      POSTGRES_PASSWORD: perf_pass
    ports:
      - "5435:5432"
    volumes:
      - postgres_perf_data:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - max_connections=200
      - -c
      - shared_buffers=256MB
      - -c
      - effective_cache_size=1GB
      - -c
      - work_mem=4MB
      - -c
      - maintenance_work_mem=64MB
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - wal_buffers=16MB
      - -c
      - default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perf_user -d perf_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local
  postgres_isolation_data:
    driver: local  
  postgres_perf_data:
    driver: local

networks:
  default:
    name: thai-energy-test-network
